ci: replaced DEVOLUTIONBOT_TOKEN secret
Devolutions/wt-distro pull request #17
Opened 2023-10-11 20:33 UTC by Sylfwood

Le secret DEVOLUTIONBOT_TOKEN va devenir read only, il ne sera donc plus possible de l'utiliser pour créer des releases. Le GITHUB_TOKEN par default devrait être suffisant.

2023-10-11 21:05 UTC, dion-gionet requested changes

2023-10-11 21:05 UTC, dion-gionet commented on .github/workflows/release-package.yml
> +    if: ${{ inputs.dry-run == false }}
Renommer `dry-run` a `dry_run` et
```suggestion
    if: ${{ !inputs.dry_run }}
```

2023-10-11 21:08 UTC, dion-gionet approved these changes

2023-11-02 18:29 UTC, awakecoding approved these changes

2023-11-02 18:29 UTC, merged